import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { baseUrl } from "@/lib/base-url";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s|Taro",
    default: "Taro"
  },
  description: "Generated by create next app",
  //ogのimageを設定する場合などに使う、ｘのプレビュー画像など
  metadataBase: new URL(baseUrl()),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <NuqsAdapter>
          <Header />
          {children}
          <Footer />
          <Toaster />
       </NuqsAdapter>
      </body>
    </html>
  );
}
